repositories:
  - name: wbstack-charts
    url: git+https://github.com/wbstack/deploy/@charts/ui?ref=main

releases:
- name: ui
  namespace: default
  chart: wbstack-charts/ui
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - "./../../../default.yaml"
