apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
  creationTimestamp: "2024-09-20T12:51:50Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api
    helm.sh/chart: api-0.31.2
  name: api-pre-install-artisan-setup
  namespace: default
  resourceVersion: "11641"
  uid: e61d73b9-169e-4bd6-8d8e-d15bdb448cc9
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: e61d73b9-169e-4bd6-8d8e-d15bdb448cc9
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: api
        app.kubernetes.io/name: api
        batch.kubernetes.io/controller-uid: e61d73b9-169e-4bd6-8d8e-d15bdb448cc9
        batch.kubernetes.io/job-name: api-pre-install-artisan-setup
        controller-uid: e61d73b9-169e-4bd6-8d8e-d15bdb448cc9
        job-name: api-pre-install-artisan-setup
      name: api
    spec:
      containers:
      - args:
        - -c
        - php artisan migrate:install; php artisan migrate --force; php artisan passport:client
          --personal --no-interaction; php artisan passport:client --password --no-interaction
        command:
        - /bin/sh
        env:
        - name: CONTAINER_ROLE
          value: app
        - name: APP_NAME
          value: WBaaS Localhost
        - name: APP_ENV
          value: local
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              key: api-app-key
              name: api-app-secrets
        - name: APP_DEBUG
          value: "false"
        - name: APP_URL
          value: http://www.wbaas.localhost
        - name: APP_TIMEZONE
          value: UTC
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis-password
        - name: REDIS_DB
          value: "2"
        - name: REDIS_CACHE_DB
          value: "3"
        - name: REDIS_PREFIX
          value: wikibase_dev_api
        - name: MAIL_MAILER
          value: smtp
        - name: MAILGUN_DOMAIN
          value: sandbox111.mailgun.org
        - name: MAILGUN_SECRET
          value: abc123
        - name: MAIL_FROM_ADDRESS
          value: noreply-local@fake.wikibase.dev
        - name: MAIL_FROM_NAME
          value: Wikibase-dev
        - name: ROUTES_LOAD_WEB
          value: "1"
        - name: ROUTES_LOAD_BACKEND
          value: "1"
        - name: LOG_CHANNEL
          value: stderr
        - name: STACKDRIVER_ENABLED
          value: "false"
        - name: STACKDRIVER_PROJECT_ID
          value: something
        - name: STACKDRIVER_LOGGING_ENABLED
          value: "false"
        - name: STACKDRIVER_TRACING_ENABLED
          value: "false"
        - name: STACKDRIVER_ERROR_REPORTING_ENABLED
          value: "true"
        - name: STACKDRIVER_KEY_FILE_PATH
          value: /var/run/secret/cloud.google.com/key.json
        - name: STACKDRIVER_ERROR_REPORTING_BATCH_ENABLED
          value: "false"
        - name: STACKDRIVER_LOGGING_BATCH_ENABLED
          value: "false"
        - name: CACHE_DRIVER
          value: redis
        - name: QUEUE_CONNECTION
          value: redis
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: api-app-jwt-secret
              name: api-app-secrets
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST_READ
          value: sql-mariadb-secondary.default.svc.cluster.local
        - name: DB_HOST_WRITE
          value: sql-mariadb-primary.default.svc.cluster.local
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: apidb
        - name: DB_USERNAME
          value: apiuser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SQL_INIT_PASSWORD_API
              name: sql-secrets-init-passwords
        image: ghcr.io/wbstack/api:10x.14.0
        imagePullPolicy: IfNotPresent
        name: pre-install-job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastProbeTime: "2024-09-20T12:57:38Z"
    lastTransitionTime: "2024-09-20T12:57:38Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 1
  ready: 1
  startTime: "2024-09-20T12:51:50Z"
  uncountedTerminatedPods: {}
