certificates:
  -
    name: wikibase-cloud-tls
    commonName: wikibase.cloud
    dnsNames:
      - '*.wikibase.cloud'
      - 'wikibase.cloud'
    secretName: wikibase-cloud-tls
    issuerRef: letsencrypt-staging #letsencrypt-prod
  - 
    name: wikibase-dev-tls
    commonName: wikibase.dev
    dnsNames:
      - '*.wikibase.dev'
      - 'wikibase.dev'
    secretName: wikibase-dev-tls
    issuerRef: letsencrypt-prod

gceProject: wikibase-cloud

gceServiceAccountSecret: secret-wikibase-dev-api
gcsApiStaticBucket: wikibase-dev-static

uiHostName: www.wikibase.dev
tlsSecret: wikibase-dev-tls

external:
  mailgun:
    domain: "wikibase.dev" # dunno if correct
    secret: "should be secret!"
  recaptcha3:
    sitekey: "dunno"
    secret: "dunno"

services:
  app:
    key: "should be secret!"
    url: https://api.wikibase.dev
    jwtSecret: "should be secret!"
  
  redis:
    port: 6379
    databases:
      apiDb: 2
      apiCacheDb: 3

  sql:
    api:
      db: apidb
      user: apiuser
      passwordSecretName: sql-apiuser
      passwordSecretKey: password