apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sql-pod-monitoring
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: sql
  podMetricsEndpoints:
  - port: metrics
    interval: 30s