# TODO we can probably eliminate the need to maintain this storage class, by using the built in new gce class https://phabricator.wikimedia.org/T292652
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: faster
  labels:
    app.kubernetes.io/managed-by: ManualGit
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true

