repositories:
- name: stable
  url: https://charts.helm.sh/stable

releases:
  - name: nginx-ingress
    namespace: kube-system
    chart: stable/nginx-ingress
    version: 1.34.3
    values:
      - "values-{{ .Environment.Name }}.yaml"

environments:
  dev:
