{{- range .Values.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: default
spec:
  commonName: {{ .commonName }}
  dnsNames:
  {{- range .dnsNames }}
  - {{ . | quote }}
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .issuerRef }}
  secretName: {{ .secretName }}
---
{{- end }}