apiVersion: batch/v1
kind: Job
metadata:
  generateName: add-pru-to-bot-group-
spec:
  template:
    metadata:
      name: add-platform-reserved-user
    spec:
      containers:
        - name: add-pru-to-bot-group
          command:
            - 'bash'
            - '-c'
            - >
                MW_INSTALL_PATH=/var/www/html/w/
                php /var/www/html/w/maintenance/createAndPromote.php
                --custom-groups=bot
                "PlatformReservedUser"
      restartPolicy: Never