---

apiVersion: batch/v1
kind: Job
metadata:
  generateName: back-up-single-wiki-
  namespace: adhoc-jobs
spec:
  ttlSecondsAfterFinished: 604800 #7days
  template:
    metadata:
      name: back-up-single-wiki
    spec:
      volumes:
        - name: temporary-backup-pvc
          persistentVolumeClaim:
            claimName: temporary-backup-pvc
      containers:
        - name: back-up-single-wiki
          image: mariadb:10.5

          command:
            - 'bash'
            - '-c'
            - |
                mysqldump ${DATABASE_NAME} > /backup/file.sql
          volumeMounts:
            - name: temporary-backup-pvc
              mountPath: "/backup/"

      restartPolicy: OnFailure

---

# some pvc stuff
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporary-backup-pvc
  namespace: adhoc-jobs
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi