apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporary-backup-pvc
  namespace: adhoc-jobs
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi