apiVersion: batch/v1
kind: Job
metadata:
  generateName: force-search-index-from-to-
  namespace: adhoc-jobs
spec:
  ttlSecondsAfterFinished: 604800
  template:
    metadata:
      name: force-search-index-from-to
    spec:
      containers:
        - name: force-search-index-from-to
          command:
            - 'bash'
            - '-c'
            - >
                MW_INSTALL_PATH=/var/www/html/w/
                php
                /var/www/html/w/extensions/CirrusSearch/maintenance/ForceSearchIndex.php
                --from="${WBS_FORCE_SEARCH_INDEX_FROM}"
                --to="${WBS_FORCE_SEARCH_INDEX_TO}"
      restartPolicy: Never
