apiVersion: batch/v1
kind: Job
metadata:
  generateName: rebuild-quantity-units-
spec:
  template:
    metadata:
      name: rebuild-quantity-units
    spec:
      ttlSecondsAfterFinished: 604800
      containers:
        - name: rebuild-quantity-units
          command:
            - 'bash'
            - '-c'
            - >
                MW_INSTALL_PATH=/var/www/html/w/
                php
                /var/www/html/w/extensions/Wikibase/repo/maintenance/rebuildEntityQuantityUnit.php
                --from-value="${WBS_UNIT_FROM}"
                --to-value="${WBS_UNIT_TO}"
      restartPolicy: Never
