apiVersion: batch/v1
kind: Job
metadata:
  generateName: reset-root-sql-secret-job-
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 604800
      containers:
        - name: reset-root-sql-secret-job
          image: docker.io/bitnami/mariadb:10.5.15-debian-10-r52
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: sql-root-password-old
                  key: mariadb-root-password
            - name: ROOT_PASSWORD_NEW
              valueFrom:
                secretKeyRef:
                  name: sql-secrets-passwords
                  key: mariadb-root-password
            - name: MYSQL_HOST
              value: sql-mariadb-primary.default.svc.cluster.local

          command:
            - 'bash'
            - '-c'
            - |+
              mysql -u root <<< "ALTER USER root IDENTIFIED BY '${ROOT_PASSWORD_NEW}'"
      restartPolicy: Never
