apiVersion: batch/v1
kind: Job
metadata:
  generateName: reset-other-sql-secrets-job-
  namespace: adhoc-jobs
spec:
  ttlSecondsAfterFinished: 604800
  template:
    spec:
      containers:
        - name: reset-other-sql-secrets-job
          image: docker.io/bitnami/mariadb:10.5.15-debian-10-r52
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: sql-secrets-passwords
                  key: mariadb-root-password
            - name: REPLICATION
              valueFrom:
                secretKeyRef:
                  name: sql-secrets-passwords
                  key: mariadb-replication-password
            - name: API
              valueFrom:
                secretKeyRef:
                  name: sql-secrets-init-passwords
                  key: SQL_INIT_PASSWORD_API
            - name: MEDIAWIKI_MANAGER
              valueFrom:
                secretKeyRef:
                  name: sql-secrets-init-passwords
                  key: SQL_INIT_PASSWORD_MW
            - name: BACKUP_MANAGER
              valueFrom:
                secretKeyRef:
                  name: sql-secrets-init-passwords
                  key: SQL_INIT_PASSWORD_BACKUPS
            - name: MYSQL_HOST
              value: sql-mariadb-primary.default.svc.cluster.local

          command:
            - 'bash'
            - '-c'
            - |+
              mysql -u root <<< "ALTER USER replicator IDENTIFIED BY '${REPLICATION}'"
              mysql -u root <<< "ALTER USER apiuser IDENTIFIED BY '${API}'"
              mysql -u root <<< \
              "ALTER USER 'mediawiki-db-manager' IDENTIFIED BY '${MEDIAWIKI_MANAGER}'"
              mysql -u root <<< "ALTER USER 'backup-manager' IDENTIFIED BY '${BACKUP_MANAGER}'"
      restartPolicy: Never
