apiVersion: batch/v1
kind: Job
metadata:
  generateName: back-up-single-wiki-
  namespace: adhoc-jobs
spec:
  ttlSecondsAfterFinished: 604800 #7days
  template:
    metadata:
      name: back-up-single-wiki
    spec:
      volumes:
        - name: temporary-backup-pvc
          persistentVolumeClaim:
            claimName: temporary-backup-pvc
      containers:
        - name: back-up-single-wiki
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: sql-secrets-passwords
                  key: mariadb-root-password
          image: mariadb:10.5

          command:
            - 'bash'
            - '-c'
            - |
                mysqldump --host sql-mariadb-secondary.default.svc.cluster.local ${DATABASE_NAME} > /backup/${DATABASE_NAME}.sql
          volumeMounts:
            - name: temporary-backup-pvc
              mountPath: "/backup/"

      restartPolicy: OnFailure
