repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - name: sql
    namespace: default
    chart: bitnami/mariadb
    version: 9.6.2
    values:
    - "sql.values.yaml.gotmpl"