#!/bin/bash

# Usage: ./update-toc.sh [target=index.md] [docs_pattern=0*.md] [marker=toc]

# This script can be used to generate a Markdown TOC for a directory
# containing markdown files and inject/update it into another document.
#
# For each file matching the given pattern the first h1 Element will be used
# to generate a list item pointing to the document's location.
# Next, the script looks for "magic" HTML comments in the target doc and replace
# the enclosed content with the updated TOC.

set -e

target=${1:-index.md}
docs_pattern=${2:-0*.md}
marker=${3:-toc}

generate_toc () {
  for doc in $docs_pattern; do
    title=$(cat $doc | grep "^#\s.*" | sed 's/# //' | sed 's/{#.*}//' | head -n 1)
    echo -n "- [$title]($doc)\n"
  done
}

sed -i "/<!-- $marker-start -->/,/<!-- $marker-end -->/c\<!-- $marker-start -->\n$(generate_toc)\<!-- $marker-end -->" $target
