apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local
spec:
  description: The local deployment of wikibase.cloud
  destinations:
  - name: in-cluster
    server: https://kubernetes.default.svc
  sourceRepos:
  - {{ .Values.repoUrls.main }}