apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.clusterUrl }}
  project: {{ .Values.environment }}
  sources:
    - repoURL: {{ .Values.repoUrls.bitnami }}
      path: bitnami/redis      
      targetRevision: HEAD
      helm:
        version: 17.3.8
        valueFiles:
          - $values/k8s/argocd/{{ .Values.environment }}/redis.values.yaml
    - repoURL: {{ .Values.repoUrls.deploy }}
      targetRevision: de/argo-redis
      ref: values

  syncPolicy:
    automated:
      selfHeal: false
      prune: true