image:
  tag: sha-52d3977

resources:
  requests:
    cpu: 1m
    memory: 6Mi
  limits:
    cpu: 10m
    memory: 20Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  hosts:
  - host: www.wbaas.localhost
    paths:
    - /*
  tls: null

ui:
  apiUrl: api.wbaas.localhost
  subdomainSuffix: ".wbaas.localhost"
  cnameConfigMapKey: cname_record
  configMapName: wbaas-ui-config
  recaptchaSitekeySecretName: recaptcha-v3-secrets
  recaptchaSitekeySecretKey: site_key

podLabels:
  sidecar.istio.io/inject: "true"
