apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "api.fullname" . }}-ingresscreator
  labels:
{{ include "api.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "api.fullname" . }}-ingresscreator
roleRef:
  kind: Role
  name: {{ include "api.fullname" . }}-ingresscreator
  apiGroup: rbac.authorization.k8s.io
