apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "api.fullname" . }}-ingresscreator
  labels:
{{ include "api.labels" . | indent 4 }}
rules:
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "create", "list"]
