# This should be run before init-sql.yaml in order to create the sql secrets / passwords
# required for the various sql services..
kind: Job
apiVersion: batch/v1
metadata:
  name: secret-creator-init-sql-apiuser
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  template:
    spec:
#      ttlSecondsAfterFinished: 600
      restartPolicy: Never
      containers:
      - name: generator
        image: replicated/k8s-secret-generator
        args:
        - '--name=sql-apiuser'
        - '--key=password'
        - '--length=32'
        - '--base64encode'
        - '--namespace=default'
  backoffLimit: 3
---
kind: Job
apiVersion: batch/v1
metadata:
  name: secret-creator-init-sql-mediawiki-db-manager
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  template:
    spec:
#      ttlSecondsAfterFinished: 600
      restartPolicy: Never
      containers:
      - name: generator
        image: replicated/k8s-secret-generator
        args:
        - '--name=sql-mediawiki-db-manager'
        - '--key=password'
        - '--length=32'
        - '--base64encode'
        - '--namespace=default'
  backoffLimit: 3
