repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: wbstack
    url: https://wbstack.github.io/charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: cetic
    url: https://cetic.github.io/helm-charts
  - name: elastic
    url: https://helm.elastic.co
  - name: codecentric
    url: https://codecentric.github.io/helm-charts

environments:
  default:
    kubeContext: INVALID-ENVIRONMENT
  production:
    kubeContext: gke_wikibase-cloud_europe-west3-a_wbaas-3
    values:
      - ./env/production/base.yaml
      - ./env/production/private.yaml
  staging:
    kubeContext: gke_wikibase-cloud_europe-west3-a_wbaas-2
    values:
      - ./env/staging/base.yaml
      - ./env/staging/private.yaml
  local:
    kubeContext: minikube-wbaas
    values:
      - ./env/local/base.yaml
      - ./env/local/private.yaml

# TODO: does this need increasing?
helmDefaults:
  timeout: 1200

# Path to helmfiles to process BEFORE releases
# All the nested state files under `helmfiles:` is processed in the order of definition.
helmfiles:
  - path: cert-manager.yaml
    values:
      - foo: null

releases:
  - name: nginx-ingress
    namespace: kube-system
    chart: stable/nginx-ingress
    version: 1.34.3
    values:
      - "env/base/nginx-ingress.values.yaml.gotmpl"

  - name: sql
    namespace: default
    # TODO reevaluate upstreaming addshore/bitnami-charts(7.3.16-mariadb-ready-check-seconds)
    # modifications
    chart: bitnami/mariadb
    version: 9.6.2
    values:
      - "env/{{ .Environment.Name }}/sql.values.yaml.gotmpl"

  - name: elasticsearch
    namespace: default
    chart: elastic/elasticsearch
    version: 6.8.18
    values:
      - "env/{{ .Environment.Name }}/elasticsearch.values.yaml.gotmpl"

  - name: redis
    # This is in the default namespace, as the default ns implies staging?
    namespace: default
    chart: bitnami/redis
    version: 15.4.1
    values:
      - "env/{{ .Environment.Name }}/redis.values.yaml.gotmpl"

  - name: platform-nginx
    namespace: default
    chart: bitnami/nginx
    version: 5.2.4
    values:
      - "env/{{ .Environment.Name }}/platform-nginx.values.yaml.gotmpl"

  - name: platform-apps-ingress
    namespace: default
    chart: ./../../charts/wikibase-ingress
    values:
      - ingressNameSuffix: {{ .Values.ingressNameSuffix | toYaml }}
      - ingressHost: {{ .Values.ingressHost | toYaml }}
      - forceSSL: {{ .Values.forceSSL | toYaml }}
      - tls: {{ .Values.tls | toYaml }}

  - name: api
    chart: wbstack/api
    version: 0.19.4
    namespace: default
    values:
      - "env/{{ .Environment.Name }}/api.values.yaml.gotmpl"

  - name: ui
    namespace: default
    chart: wbstack/ui
    version: 0.2.13
    values:
      - "env/{{ .Environment.Name }}/ui.values.yaml.gotmpl"

  - name: mediawiki-137-fp
    namespace: default
    chart: wbstack/mediawiki
    version: 0.10.1
    values:
      - "env/{{ .Environment.Name }}/mediawiki-137-fp.values.yaml.gotmpl"

  - name: queryservice-ui
    namespace: default
    chart: wbstack/queryservice-ui
    version: 0.1.3
    values:
      - "env/{{ .Environment.Name }}/queryservice-ui.values.yaml.gotmpl"
  - name: queryservice
    namespace: default
    chart: wbstack/queryservice
    version: 0.1.3
    values:
      - "env/{{ .Environment.Name }}/queryservice.values.yaml.gotmpl"
  - name: queryservice-gateway
    namespace: default
    chart: wbstack/queryservice-gateway
    version: 0.1.2
    values:
      - "env/{{ .Environment.Name }}/queryservice-gateway.values.yaml.gotmpl"
  - name: queryservice-updater
    namespace: default
    chart: wbstack/queryservice-updater
    version: 0.1.2
    values:
      - "env/{{ .Environment.Name }}/queryservice-updater.values.yaml.gotmpl"

  - name: tool-cradle
    namespace: default
    chart: wbstack/tool-cradle
    version: 0.1.2
    values:
      - "env/{{ .Environment.Name }}/tool-cradle.values.yaml.gotmpl"
  - name: tool-widar
    namespace: default
    chart: wbstack/tool-widar
    version: 0.2.0
    values:
      - "env/{{ .Environment.Name }}/tool-widar.values.yaml.gotmpl"
  - name: tool-quickstatements
    namespace: default
    chart: wbstack/tool-quickstatements
    version: 0.2.3
    values:
      - "env/{{ .Environment.Name }}/tool-quickstatements.values.yaml.gotmpl"

  - name: wbaas-backup
    namespace: default
    chart: wbstack/wbaas-backup
    version: 0.0.3
    values:
      - "env/{{ .Environment.Name }}/wbaas-backup.yaml.gotmpl"
