environments:
  default:
    kubeContext: INVALID-ENVIRONMENT
  production:
    kubeContext: gke_wikibase-cloud_europe-west3-a_wbaas-3
    values:
      - ./env/production/base.yaml
      - ./env/production/private.yaml
  staging:
    kubeContext: gke_wikibase-cloud_europe-west3-a_wbaas-2
    values:
      - ./env/staging/base.yaml
      - ./env/staging/private.yaml
  local:
    kubeContext: minikube-wbaas
    values:
      - ./env/local/base.yaml
      - ./env/local/private.yaml

---

releases:
  - name: istio-base
    namespace: istio-system
    chart: istio/base
    version: 1.17.1
    set:
      - name: installCRDs
        value: true
