releases:
  - name: adminer-cetic
    namespace: default
    installed: {{ eq .Environment.Name "local" | toYaml }}
    chart: cetic/adminer
    version: v0.2.1
    values:
      - env/local/adminer-cetic.values.yaml.gotmpl

  - name: mailhog
    installed: {{ eq .Environment.Name "local" | toYaml }}
    namespace: default
    chart: codecentric/mailhog
    version: 5.0.1
    values:
      - env/local/mailhog.values.yaml.gotmpl