releases:
  - name: adminer-cetic
    namespace: default
    chart: cetic/adminer
    version: v0.1.7
    values:
      - "env/local/adminer-cetic.values.yaml.gotmpl"

  - name: mailhog
    namespace: default
    chart: codecentric/mailhog
    version: 5.0.1
    values:
      - env/local/mailhog.values.yaml
  - name: nginx-ingress
    chart: stable/nginx-ingress
    values:
      - "env/local/nginx-ingress.values.yaml.gotmpl"
  - name: elasticsearch
    chart: elastic/elasticsearch
    values:
      - "env/local/elasticsearch.values.yaml.gotmpl"
