releases:
  - name: prometheus-operator-crds
    namespace: monitoring
    version: 2.0.0
    chart: prometheus-community/prometheus-operator-crds
    installed: {{ ne .Environment.Name "production" | toYaml }}
