releases:
  - name: prometheus-operator-crds
    namespace: monitoring
    version: '{{ if eq .Environment.Name "production" }} 2.0.0 {{ else }} 9.0.0 {{ end }}'
    chart: prometheus-community/prometheus-operator-crds
