repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
- name: redis
  namespace: default
  chart: bitnami/redis
  version: 10.5.14
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../private-production.yaml