apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "superset.fullname" . }}-config
  labels:
    {{- include "superset.labels" . | nindent 4 }}
data:
  entrypoint.sh: |
    {{- tpl .Values.entrypoint . | nindent 4 }}
  config.py: |
    {{- tpl .Values.config . | nindent 4 }}
