replicaCount: 1

image:
  repository: ghcr.io/wbstack/ui
  tag: 2.4.1
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []
