{{ if .Values.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: {{ .Values.peerAuthentication.mtls.mode }}
{{ end }}
