apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/argocd-apps
    repoURL: {{ .Values.repoUrls.main }}
    targetRevision: ta/argo-apps-ui # debug! needs to be set to HEAD
    helm:
      values: |
{{ toYaml .Values | indent 8 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false