apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/argocd-apps
    repoURL: {{ .Values.repoUrls.main }}
    targetRevision: de/argo-apps-ui # debug! needs to be set to HEAD
    helm:
      valueFiles:
        - env/production/ui.values.yaml
        - env/local/ui.values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: false