apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: {{ .Values.environment }}
  source:
    path: charts/argocd-apps
    repoURL: {{ .Values.repoUrls.deploy }}
    targetRevision: de/argo-ui-simple # debug! needs to be set to HEAD
    helm:
      parameters:
        - name: helm.debug
          value: "true"
      values: |
{{ toYaml .Values | indent 8 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false