apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-styles-cm
  namespace: argocd
data:
  local.css: |
    .ui-banner {
        background-color:#6d7f8b;
        
        a {
          color:white;
        }
    }

  staging.css: |
    .ui-banner {
        background-color:#e18900;

        a {
          color:white;
        }
    }

  production.css: |
    .ui-banner {
        background-color:#d93f4a;

        a {
          color:white;
        }
    }