on: push
name: Check values files
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Create helmfile docker shim
        run: >
          echo 'docker run --rm -v "${PWD}:/wd" ghcr.io/helmfile/helmfile:latest helmfile' \
            > /usr/bin/helmfile
          chmod a+x /usr/bin/helmfile
      - name: Create yq docker shim
        run: >
          echo 'docker run --rm -v "${PWD}:/wd" --entrypoint yq ghcr.io/linuxserver/yq:latest' \
            > /usr/bin/yq
          chmod a+x /usr/bin/yq
      - name: Diff generated value files
        run: >
          for env_dir in k8s/argocd/*; do
            env=$(basename $env_dir)
            for release_file in $env_dir/*.values.yaml; do
              release=$(basename $release_file .values.yaml)
              tmp_values_file=/tmp/$env.$release.yml
              echo checking $k - [$env] [$release]
              ./bin/generate-values "$env" "$release" $tmp_values_file
              diff tmp_values_file $release_file
            done
          done
