on: push
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Check if Terraform files are properly formatted
        run: terraform fmt -recursive -check tf
