on: push
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3

      - name: Install Opentofu
        uses: opentofu/setup-opentofu@v1
      - name: Check if Opentofu files are properly formatted
        run: tofu fmt -recursive -check tf

      - name: Install shellcheck # https://github.com/koalaman/shellcheck/wiki/GitHub-Actions#version-pinning
        run: |
          VERSION="v0.11.0"
          wget "https://github.com/koalaman/shellcheck/releases/download/$VERSION/shellcheck-$VERSION.linux.x86_64.tar.xz"
          tar -xf "shellcheck-$VERSION.linux.x86_64.tar.xz"
          sudo cp "shellcheck-$VERSION/shellcheck" /usr/bin/
      - name: Check Shell scripts
        run: ./bin/run-shellcheck
