on: push
name: Test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
